### ISSUE TITLE
Allow cross origin requests

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Tracker-Backend#10]
Currently the tracker api does not allow cross origin requests. Please allow them so we can test fetching data from localhost 

I am trying to fetch from `localhost:5173` using
```javascript
fetch("https://api.mcsynergy.nl/tracker/message/get/all" + new URLSearchParams({
    "page": "0",
    "size": "100"
}), {
    method: "GET",
    headers: {
        authorization: `Bearer ${idToken}`
    }
}).then(response => response.json())
.then(data => console.log(data))
```

**Comment by crazyvinvin** [comment]
`AllowedHosts` has nothing to do with cors, but with where the app is allowed to be hosted. You need to enable cors using the useCors method on the built app.

**Comment by crazyvinvin** [comment]
I have tested it locally with the tracker on a basic endpoint without any paramaters or headers and it works with postman, but doesn't from localhost in the browser (on a different port, so cross origin)

**Comment by Josian2004** [comment]
fixed with pr
