### ISSUE TITLE
incorrect location when no location exists

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Tracker-Backend#22]
When requesting the location of a computer that does not have a location, a 404 response should be send. To me it looks like i'm getting coordinates 0, 0, 0, for all the computers without a location, this could be very misleading.

I could of course choose to not show coordinates 0, 0, 0. But if a turtle every DOES have coordinates 0, 0, 0, this would be incorrect.

Please make sure that when a computer does not have a last location, a 404 is send back.

**Comment by Josian2004** [comment]
this was due to a bug in the lua library, I fixed it in the lib so it is fixed when a computer has updated their script with the new lib. When every computer is updated, we need to whipe the location collection otherwise the issue will remain

**Comment by Josian2004** [comment]
to be clear, the issue will remain as long as there are outdated computers in the Minecraft server and there isn't something I can do about that so don't reopen this issue unless you think you found another bug :)
