### ISSUE TITLE
Endpoint for sending commands to multiple turtles

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Tracker-Backend#25]
An endpoint for sending commands to turtles would be very handy in the case of a code deployment. Lets say I want to update the pumpkin farmers, I have to reboot each one separately. Would be nice If  we could reboot all harvesting turtles from a system in one go. Most of that would be handled in the frontend but an endpoint that can receive 1 command + multiple turtle ids would be nice.

TLDR:
Endpoint with a list of turtle ids and 1 command as parameters.

**Comment by Josian2004** [comment]
added
