### ISSUE TITLE
Dont crash turtles on purpose

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Tracker-Backend#9]
When an exception is thrown and catched. The tracker currently handles the exception and sends the error to the tracker server. It then proceeds to crash it, instead of leaving it on, waiting for further instructions. 

When a turtle crashes mid run, I want to be able to perform atleast basic actions on it, like rebooting. Most scripts should have an initialize function good enough to run back to the starting position, instead of me having to retreive 16 turtles. 

When a turtle or computer is terminated by hand, it should ofcourse terminate.

**Comment by Josian2004** [comment]
turtle now doesn't crash when an exception is thrown, I haven't added any more functionality to it yet but I will in the future

**Comment by Josian2004** [comment]
added to lib in dev
